### ISSUE TITLE
404 File not found on arekushi.github.io

### ISSUE THREAD

**Issue by FH089** [Arekushi/Finite-State-Machine-Arduino#1]
Hey 
I just came across the website https://arekushi.github.io/Finite-State-Machine-Arduino/, Below is an "Install" article linked to it.
![image](https://user-images.githubusercontent.com/50920534/111370808-f5af7600-8698-11eb-98ba-323f0ec38751.png)

This leads to the following page(URL: https://arekushi.github.io/Finite-State-Machine-Arduino/install.html).
![image](https://user-images.githubusercontent.com/50920534/111371098-42934c80-8699-11eb-8d91-34e7a5c6ceae.png)
 
Clicking Continue Reading now leads to the following error message.

![image](https://user-images.githubusercontent.com/50920534/111371332-8a19d880-8699-11eb-9026-d4bcba9aa44f.png)

**Comment by Arekushi** [comment]
Hi,

I haven't finished the article yet, do you need help with something?

Em ter., 16 de mar. de 2021 às 16:54, Fabian Hofstetter <
***@***.***> escreveu:

**Comment by FH089** [comment]
Hi 
Sorry I thought the URL was corrupt, the issue can be closed

Greetings

**Comment by FH089** [comment]
-
